<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by System</title>
</head>
<body>
    <h1>{{ $content['name'] }}</h1>
    <p>{{ $content['info'] }}</p>
    <p>Thank you</p>
</body>
</html> 