<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by System</title>
</head>
<body>
    <h2>Dear {{ $content['name'] }}, </h2>
    <h3>{{ $content['welcome-greeting'] }}</h3>
    <p>{{ $content['info'] }}</p>
    <p>{{ $content['end-greeting'] }}</p>
</body>
</html> 